server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jxb120608
    url: jdbc:mysql://localhost:3306/myshop?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # redis配置
  data:
    redis:
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0


# 配置mybatis实体和xml映射
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: myshoptoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# 配置文件上传路径
fileBaseUrl: http://localhost:8080

alipay:
  #应用ID
  appId: 9021000143662176
  #商户私钥
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwb+AhN2ksQKHaPKfkwR6P46eq+Jb4W68qiLx6m7sE4d1MYMCWVPpSbTqrWu408ZLuFz0m6QSNL7Cs5dYCegZ+Zhq2kd0RHZ1nlyNn3p4IXetcKs6qHhUXHFC4MIjAfiZDmiPKGu5pIYpwdR1DuUCGSB9xHx9bSChS9G5OLKJ6iPlt/WhTHg/Gt92JMTT/9hcYVaiMsHET6ixSFUb2JQ9Mc5vmswmplpyRGeZc9L845QsOM+8LsByZqNSNxzNBUksjcIO/mWQH+yZOHIb2bbKOZeawLQ7ovA6QXsaMjD7TQ/mRuG1NoI4B3MYyQ4UNRIZt+BNwJiu/vfhsAb/SfusPAgMBAAECggEAZZg1/cpzVBjvWcP9hToyh/Y1sLwt6lqY1awgo5USrnAERpubqbTK4zWkR9E3QuMrkM9u1f3tMgMY/6Xkgk6TeKsAjMoW+mkMHv8nUwMcCoNSKCM6Fzj1OfaDAFxqEjVRgTG7k//H8l9u4Ox+6mU8o1XaTP/3xU8acRHwhjEradSKsJEFA0Xjisf2QbkPQ9PHzWIYFD6ZWv8BT6Wo5nFAkn+eEFq2cqVwzqWYW61vX4MIbiWv3Pl0IxdZMi0Nna+f0rGaG2Qn6NGj/m0LZN73xpmei1qJowLrDpdGTfUmcg4njnancEJ5Z0ooNId+teh7jGlOxXVNkCHCs688qytu8QKBgQDbpG4seFKVnzw4RIYYudDT/YO9egaZHaZlxGeA/egphgzXAfaOyTeqNGA4DyF7rGQDCoeIdpheXtzB0wkPKXnWkBBeHSvVtRQ4vWFfSSHQjDFerh8yJ2ysR9MqkvPRyHgC/Asj/I6e4U+XP+/CaY9bA5YL3zwQKdV2Piuls56U9wKBgQDNpJOEaYGTZiJ6qU+ECGtlPxm1P3x0uX/3UxEosYr+E4SwSNbkAKDqgYgM9Nf4smOFrtIqgCmf2SCqROEiGbkXJ2bfAG3fbJvhUfXbOx9q3+PdPWJ4SI4IIwrTksiwnTiInzogGVQGKqDflcqf0oO56OwH8NY5bK5ReaVIkQUMqQKBgA1mJIp19KPICQZtt7h+bWzhRE4kyY5Brsr6hk3qL2WJFfNv3TisscaiV1RUJ/jBdYBx/f6nLXhkVRdF5oGUSCh8tWLoaKoq18b2VqBXd8afJsvd121Z1llUMF+ig1lC339fHNbfK1wp5o8ViWzUv7gPqfGjdqiNxMXn2QXMxVnVAoGBAIlBFWzFdsTI4K56HyaC8BttmF0O+KR3w19yQ/ujNKAMqv12QGeBu+WJeyMasKO/fQmW+5N+Y0nbhB/hRVqbTJyVoeWpxavgM9KZ/7zJo1iUAuSBuh2KX7IyoWFBkU3AQiF+FS+jeB99iE5zDgDKYz1Mp21NY86EKX0b8iOTF4mxAoGBAKo1iBEGK0/dAJKRhfSsvb0fZul5uphjATD5ePRDroaAszc2dAeyQSWlQG6WHgWui4IAzIRvCVXQYHiZdo4nBKO7BXMQ2ixwryMg3BGtn2i+2KgNSrgqhRrqUq4ILe0r9GHPit5ODZ8ZwOVGi6mN1GXbG7//xZ1s7acquzDnsN/i
  #支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk3Ot4c2YPeS23qDja6W4L7SWyMxfMKGm5N+Ha0iJlRehc1mjgwtfqOn0I6OIjhITdK/jaO+8gE4Wxfzsan4EgEXsaeJO8Hg6BV06mPM9INQXlo2t2pHRWatz+raiJ+ge1HxoxODva7ratn1fqvLqoG9CkDIzN+NHxdX+y9bQs/DiEShGWoJpYu7ipHpDuTsqz6x0ES/xWviuA3fdmN1S5g+ydrzDlgiVL6SjM/uOHhdOZ8HuJ82SnLi4Y20wlvsZr2COx3dcmDukZzNCbg31b53AZ4dlApHTHDMZ7oUe5piOXG1RRWc8Ohhth8w9QPkxCBD3XN1ZYuVq3eeQD086xQIDAQAB
  #本地回调地址 必须是公网地址
  notifyUrl: http://iddbi4.natappfree.cc/alipay/notify


